#!/bin/bash

WORKDIR="t2"
REMOTE_DIR="~/Desktop/$WORKDIR"

function setup() {
    echo "Preparing VM env."
    ssh -t -q aluno@127.0.0.1 "cd ~/Desktop && mkdir -p $WORKDIR"
}

function vmdeploy() {
    # Send files
    echo "Deploying files to $REMOTE_DIR"
    ssh -t -q aluno@127.0.0.1 "cd $REMOTE_DIR && rm -rf *"
    scp -r * aluno@127.0.0.1:$REMOTE_DIR
}

function vmrun() {
    CMD="$*"
    echo "Executing \"$CMD\" at $REMOTE_DIR."
    REMOTECMD="cd $REMOTE_DIR && $CMD"
    ssh -t -q aluno@127.0.0.1 "$REMOTECMD"
}

setup
